### ISSUE TITLE
Warn users about installation size

### ISSUE THREAD

**Issue by albertogasparin** [SebastianS90/webpack-polyfill-injector#1]
Your plugin is really handy, however you should warn users that it will install 200+ dependencies. At least in my case, `polyfill-service` I ended up installing copies of babel, mysql2, mocha, etc...
A bit to much for solving a 1KB polyfill requirement

**Comment by SebastianS90** [comment]
Thanks for the report, I added a small warning next to the installation instructions in the readme document.

If you know a way to pull in a package without its dependencies please let me know. I don't need any functionality of `polyfill-service` itself, only the files from the `polyfills` folder of that package.

**Comment by albertogasparin** [comment]
That was quick! Well done 😉 
Well, I don't think it is possible with the standard `package.json` way, but you could:
- either create your own fork of `polyfill-service`, getting rid of (nearly all) dependencies on `package.json` and point to that fork in `webpack-polyfill-injector`. The downside is that you will need to manually maintain the fork up to date
- otherwise use a post install script to fetch latest `polyfill-service` release, extract it to node_modules and patch package.json on the fly. With this solution you avoid npm dependency management, but you also lose proper versioning and package-lock/shrimpwrap

**Comment by SebastianS90** [comment]
Hmm yeah, these are the options I've thought about before as well. But (1) is too much work for me and (2) is pretty bad because of the versioning problem.

The only option that would be conform to the standard way is probably to ask the `polyfill-service` authors whether they can extract the polyfills to an extra package with no dependencies and then pull in that package for their `polyfill-service`. Then I could use the light package here.

I use this package here as part of my continuous deployment. The CI server installs the npm packages (mostly from a persistent cache) and builds the final javascript files. Then it creates a package containing only the compiled files. The `node_modules` folder is not contained in my final build. So it doesn't really matter to me that there are lots of additional packages pulled in.
But for apps that need the node_modules folder in their final build it is indeed a problem.

**Comment by albertogasparin** [comment]
Indeed having FT splitting its code would be better.
Looks like someone [already asked for it](https://github.com/Financial-Times/polyfill-service/issues/1265), so you should probably add a comment there in order to "push" for a resolution
