### ISSUE TITLE
Version 1.0.2 contains breaking changes

### ISSUE THREAD

**Issue by janjaap** [SebastianS90/webpack-polyfill-injector#15]
When comparing the package.json file between versions 1.0.1 and 1.0.2, there is a change in Webpack version; from 3.10.0 to 4.6.0. This shouldn't be the case in a patch version.

**Comment by SebastianS90** [comment]
In webpack-polyfill-injector v1.0.2 there is no dependency or peerDependency on Webpack at all, only a devDependency. Therefore, when your package depends on webpack-polyfill-injector v1.0.2 it does not require any Webpack at all.

The commit that changed the devDependency is 05f2ec80e34663eaa9dc7d82a4b5c9ad4ba9f2bd. As you can see, I updated the testsuite to test webpack-polyfill-injector against Webpack 4 instead of Webpack 3.

webpack-polyfill-injector v1.0.2 works with Webpack 3 and Webpack 4 (the same holds for webpack-polyfill-injector v1.0.1).
However, both v1.0.1 and v1.0.2 might no longer work with a future version of Webpack, because they use an API which is already deprecated as of Webpack 4. So actually I should have put a peerDependency on Webpack 3 || 4, but adding this in a patch or minor release is not possible.

[webpack-polyfill-injector v2.0.0 ](https://github.com/SebastianS90/webpack-polyfill-injector/releases/tag/v2.0.0) (a new major version) adds a peerDependency on Webpack 4 and uses the new Webpack 4 `.hooks` API instead of the deprecated `.plugin` API (see [diff](https://github.com/SebastianS90/webpack-polyfill-injector/compare/v1.0.2...v2.0.0)). This is a breaking change and properly released as a new major version.

Please let me know if you have any problems using v1.0.2 where v1.0.1 or v1.0.0 has worked before, i.e. you have hit a real breaking change.

**Comment by janjaap** [comment]
@SebastianS90 Thanks for reply, appreciate it. I think I jumped the gun on this one; I was using a dependant package that had version 1.0.2 of the `webpack-polyfill-injector` whereas my main package was still referring to 1.0.1. Apologies for the confusion.
