### ISSUE TITLE
Load polyfills that are not shipped in polyfill-service itself but referenced in the config.json file

### ISSUE THREAD

**Issue by andyo729** [SebastianS90/webpack-polyfill-injector#2]
When I include support for `Promise` I get an error that the module cannot be found. I checked out `polyfill-service` and it appears that it is pointed to the wrong path. For example, `Promise` should go to: 'polyfill-service/polyfills/Promise/prototype/finally/polyfill'.

**Comment by andyo729** [comment]
So, if I use `Promise.prototype.finally` in the polyfills array it appears to work. Might just be a matter of updating your docs.

**Comment by SebastianS90** [comment]
You are right, there is a problem with the `Promise` polyfill. But simply using `Promise.prototype.finally` is not the correct solution, because that actually is a different polyfill (that one only contains the `finally` method and expects `then` and `catch` to be implemented by the browser. The `Promise` polyfill provides all three methods.)

Polyfill-service [used to have](https://github.com/Financial-Times/polyfill-service/blob/v3.8.1/polyfills/Promise/polyfill.js) a file at `polyfill-service/polyfills/Promise/polyfill.js`, this is the file which my injector package tries to load. But the file has been removed in later versions of `polyfill-sevice`.
It looks like they now also [reference](https://github.com/Financial-Times/polyfill-service/blob/v3.22.0/polyfills/Promise/config.json#L32-L35) polyfills from external packages, i.e. the `Promise` polyfill can actually be found at `node_modules/yaku/dist/yaku.browser.global.min.js`.

The solution for this issue here will be to edit [this line](https://github.com/SebastianS90/webpack-polyfill-injector/blob/v0.0.3/src/index.js#L91) such that:
* we first check whether the `polyfill.js` file exists, if so then simply use it
* otherwise read the `config.json` file and do whatever is specified in the `install` section to obtain the polyfill (see [documentation](https://polyfill.io/v2/docs/contributing/authoring-polyfills#configuration))


I guess I'll have time to work on this next weekend.

**Comment by SebastianS90** [comment]
There was actually a very simple solution to this problem: `polyfill-service` uses a `postinstall` script that compiles all polyfills to `polyfill-service/polyfills/__dist/`. So we can just take the files from there...
