### ISSUE TITLE
Webpack 3.11 crashes on Object.setPrototypeOf polyfill

### ISSUE THREAD

**Issue by eugene159** [SebastianS90/webpack-polyfill-injector#22]
Webpack 3.11, webpack-polyfill-injector 1.0.2
When I'm adding Object.setPrototypeOf to polyfills array Webpack crashes with the error:

ERROR in (webpack)-polyfill-injector/src/loader.js?{"modules":["./ClientApp/boot.ts"]}
    Module parse failed: Unexpected token (162:38)
    You may need an appropriate loader to handle this file type.
    |           return false;
    | }())) ||
    |         /* Object.setPrototypeOf */ !();
    | }.call(window)) {
    |     var js = document.createElement('script');

![image](https://user-images.githubusercontent.com/16325647/45010854-59369400-afc4-11e8-980d-4030e9730056.png)

If I comment out Object.setPrototypeOf then Webpack runs successfully.

![image](https://user-images.githubusercontent.com/16325647/45010891-8daa5000-afc4-11e8-8af3-ac22347fb208.png)

I'm trying to make my Angular app work in IE11, no luck so far :(

![image](https://user-images.githubusercontent.com/16325647/45010936-cba77400-afc4-11e8-98c4-f60b815f3042.png)

**Comment by SebastianS90** [comment]
I found the problem and it is in `polyfill-library`: The Polyfill `Object.setPrototypeOf` has no detector. Have a look at [the detector for `Object.getPrototypeOf`](https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Object/getPrototypeOf/detect.js).
There should be a similar `detect.js` file [here](https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Object/setPrototypeOf/). Without a detector, we cannot conditionally include the polyfill because we do not know how to check whether the browser supports it natively. You can send a PR to `polyfill-library` adding the missing file.

Added a clear error message in ed958094f85b865d25563d8b3420d058baf99d11. Closing as it is a upstream issue.
