### ISSUE TITLE
Differents services or inner polyfill-service

### ISSUE THREAD

**Issue by flintforge** [SebastianS90/webpack-polyfill-injector#4]
Any way to get some polyfills in one service and the other with the polyfill-service delivered in the package ?

something like this perhaps ?
```
 new PolyfillInjectorPlugin([{
        polyfills: ['Promise'],
        service:'./js/promise.min.js'
    }, 
    {
        polyfills: [
            'String/prototype/startsWith',
        ],
    }])
```

**Comment by SebastianS90** [comment]
I'm currently working on the next release of this plugin. It will be possible to create one asset for each combination of needed polyfills. For example, if you configure that polyfills A, B and C are required, then webpack bundles assets for A, B, C, AB, AC, BC, ABC and the entry chunk will load the required one. The server does not need to do anything special because it just serves a static file that is contained in the bundle.
Of course, the overall bundle size will increase, but only one file per client is needed and it does not contain unnecessary polyfills, so it actually saves bandwidth.

Would that fit your needs, or do you need to rely on a polyfill-service that dynamically serves the files instead of generating every possible option at build time?

(There will still be the option to bundle only a single file contrasting all polyfills)

**Comment by SebastianS90** [comment]
The new version `1.0.0` with the change mentioned above is currently in the [`develop` branch](https://github.com/SebastianS90/webpack-polyfill-injector/tree/develop) and can be installed using the `@beta` tag:
```
yarn add webpack-polyfill-injector@beta --dev
npm install webpack-polyfill-injector@beta --save-dev
```

Does that fit the needs requested here?

**Comment by SebastianS90** [comment]
`1.0.0` has been released and supports the following configuration:

```javascript
    entry: {
        entry1: `webpack-polyfill-injector?${JSON.stringify({
            modules: ['./src/entry1.js'],
            polyfills: ['Promise', 'Array.prototype.find'],
        })}!`,
        entry2: `webpack-polyfill-injector?${JSON.stringify({
            modules: ['./some-vendor-script-that-will-be-loaded-first.js', './src/entry2.js'],
            polyfills: ['String.prototype.startsWith'],
        })}!`,
    },
```

If you have other requirements that are not possible with the new update then please open a new issue explaining the use-case. Thanks!
